#coding:utf8


import scrapy
import re, json
from scrapy import Request
import os,sys
import urllib

class baikePicSpider(scrapy.Spider):
    reload(sys)     
    sys.setdefaultencoding('utf-8') 

    name = "baikePic"
    allowed_domains = ["*"]
    start_urls = [
        #"http://127.0.0.1/s1.html"
	"https://baike.baidu.com/item/蓟",
	"https://baike.baidu.com/item/云实",
	"https://baike.baidu.com/item/兰花",
	"https://baike.baidu.com/item/冬红",
	"https://baike.baidu.com/item/凌霄",
	"https://baike.baidu.com/item/凤丹",
	"https://baike.baidu.com/item/刺桐",
	"https://baike.baidu.com/item/刺槐",
	"https://baike.baidu.com/item/合欢",
	"https://baike.baidu.com/item/含笑",
	"https://baike.baidu.com/item/地黄",
	"https://baike.baidu.com/item/夏堇",
	"https://baike.baidu.com/item/姜花",
	"https://baike.baidu.com/item/射干",
	"https://baike.baidu.com/item/小檗",
	"https://baike.baidu.com/item/建兰",
	"https://baike.baidu.com/item/扶桑",
	"https://baike.baidu.com/item/昙花",
	"https://baike.baidu.com/item/春兰",
	"https://baike.baidu.com/item/月季",
	"https://baike.baidu.com/item/木棉",
	"https://baike.baidu.com/item/木槿",
	"https://baike.baidu.com/item/木荷",
	"https://baike.baidu.com/item/杏花",
	"https://baike.baidu.com/item/杠柳",
	"https://baike.baidu.com/item/桂花",
	"https://baike.baidu.com/item/桃花",
	"https://baike.baidu.com/item/桔梗",
	"https://baike.baidu.com/item/梅花",
	"https://baike.baidu.com/item/梓树",
	"https://baike.baidu.com/item/梨花",
	"https://baike.baidu.com/item/棣棠",
	"https://baike.baidu.com/item/檵木",
	"https://baike.baidu.com/item/毛鹃",
	"https://baike.baidu.com/item/水仙",
	"https://baike.baidu.com/item/灰莉",
	"https://baike.baidu.com/item/牡丹",
	"https://baike.baidu.com/item/牵牛",
	"https://baike.baidu.com/item/猬实",
	"https://baike.baidu.com/item/玉兰",
	"https://baike.baidu.com/item/玫瑰",
	"https://baike.baidu.com/item/球兰",
	"https://baike.baidu.com/item/甘菊",
	"https://baike.baidu.com/item/白掌",
	"https://baike.baidu.com/item/白芨",
	"https://baike.baidu.com/item/百合",
	"https://baike.baidu.com/item/睡莲",
	"https://baike.baidu.com/item/瞿麦",
	"https://baike.baidu.com/item/石竹",
	"https://baike.baidu.com/item/石蒜",
	"https://baike.baidu.com/item/稠李",
	"https://baike.baidu.com/item/紫荆",
	"https://baike.baidu.com/item/紫萼",
	"https://baike.baidu.com/item/紫藤",
	"https://baike.baidu.com/item/红掌",
	"https://baike.baidu.com/item/红蓼",
	"https://baike.baidu.com/item/红蕉",
	"https://baike.baidu.com/item/结香",
	"https://baike.baidu.com/item/络石",
	"https://baike.baidu.com/item/翠菊",
	"https://baike.baidu.com/item/翠雀",
	"https://baike.baidu.com/item/芍药",
	"https://baike.baidu.com/item/苹婆",
	"https://baike.baidu.com/item/茑萝",
	"https://baike.baidu.com/item/茶梅",
	"https://baike.baidu.com/item/茼蒿",
	"https://baike.baidu.com/item/荷花",
	"https://baike.baidu.com/item/莪术",
	"https://baike.baidu.com/item/菊花",
	"https://baike.baidu.com/item/萱草",
	"https://baike.baidu.com/item/葛根",
	"https://baike.baidu.com/item/葱兰",
	"https://baike.baidu.com/item/葱莲",
	"https://baike.baidu.com/item/蕙兰",
	"https://baike.baidu.com/item/蕺菜",
	"https://baike.baidu.com/item/藿香",
	"https://baike.baidu.com/item/蜀葵",
	"https://baike.baidu.com/item/蜡梅",
	"https://baike.baidu.com/item/蜡菊",
	"https://baike.baidu.com/item/角蒿",
	"https://baike.baidu.com/item/费菜",
	"https://baike.baidu.com/item/郁李",
	"https://baike.baidu.com/item/铁兰",
	"https://baike.baidu.com/item/铃兰",
	"https://baike.baidu.com/item/锦葵",
	"https://baike.baidu.com/item/雏菊",
	"https://baike.baidu.com/item/韭兰",
	"https://baike.baidu.com/item/韭莲",
	"https://baike.baidu.com/item/风兰",
	"https://baike.baidu.com/item/麦李",
	"https://baike.baidu.com/item/黄兰",
	"https://baike.baidu.com/item/黄堇",
	"https://baike.baidu.com/item/黄槐",
	"https://baike.baidu.com/item/黄槿",
	"https://baike.baidu.com/item/黄蝉",
	"https://baike.baidu.com/item/一串红",
	"https://baike.baidu.com/item/一品红",
	"https://baike.baidu.com/item/万代兰",
	"https://baike.baidu.com/item/万寿菊",
	"https://baike.baidu.com/item/三色堇",
	"https://baike.baidu.com/item/东野菰",
	"https://baike.baidu.com/item/串钱柳",
	"https://baike.baidu.com/item/九里香",
	"https://baike.baidu.com/item/五色梅",
	"https://baike.baidu.com/item/仙人指",
	"https://baike.baidu.com/item/仙客来",
	"https://baike.baidu.com/item/佛甲草",
	"https://baike.baidu.com/item/使君子",
	"https://baike.baidu.com/item/假昙花",
	"https://baike.baidu.com/item/假苹婆",
	"https://baike.baidu.com/item/假连翘",
	"https://baike.baidu.com/item/假酸浆",
	"https://baike.baidu.com/item/八仙花",
	"https://baike.baidu.com/item/六倍利",
	"https://baike.baidu.com/item/六月雪",
	"https://baike.baidu.com/item/凤仙花",
	"https://baike.baidu.com/item/凤凰木",
	"https://baike.baidu.com/item/凤尾兰",
	"https://baike.baidu.com/item/凤眼莲",
	"https://baike.baidu.com/item/刺儿菜",
	"https://baike.baidu.com/item/剪秋罗",
	"https://baike.baidu.com/item/勋章菊",
	"https://baike.baidu.com/item/勿忘我",
	"https://baike.baidu.com/item/千日红",
	"https://baike.baidu.com/item/午时花",
	"https://baike.baidu.com/item/半支莲",
	"https://baike.baidu.com/item/半枝莲",
	"https://baike.baidu.com/item/卡特兰",
	"https://baike.baidu.com/item/叶子花",
	"https://baike.baidu.com/item/吊钟花",
	"https://baike.baidu.com/item/向日葵",
	"https://baike.baidu.com/item/君子兰",
	"https://baike.baidu.com/item/含笑花",
	"https://baike.baidu.com/item/含羞草",
	"https://baike.baidu.com/item/唐菖蒲",
	"https://baike.baidu.com/item/四海波",
	"https://baike.baidu.com/item/夜合花",
	"https://baike.baidu.com/item/大丽花",
	"https://baike.baidu.com/item/大岩桐",
	"https://baike.baidu.com/item/大滨菊",
	"https://baike.baidu.com/item/大花葱",
	"https://baike.baidu.com/item/天人菊",
	"https://baike.baidu.com/item/天竺葵",
	"https://baike.baidu.com/item/头花蓼",
	"https://baike.baidu.com/item/夹竹桃",
	"https://baike.baidu.com/item/孔雀草",
	"https://baike.baidu.com/item/小冠花",
	"https://baike.baidu.com/item/小苍兰",
	"https://baike.baidu.com/item/山丹花",
	"https://baike.baidu.com/item/山指甲",
	"https://baike.baidu.com/item/山茶花",
	"https://baike.baidu.com/item/帝王花",
	"https://baike.baidu.com/item/康乃馨",
	"https://baike.baidu.com/item/彼岸花",
	"https://baike.baidu.com/item/悬铃花",
	"https://baike.baidu.com/item/报春花",
	"https://baike.baidu.com/item/接骨木",
	"https://baike.baidu.com/item/接骨草",
	"https://baike.baidu.com/item/文冠果",
	"https://baike.baidu.com/item/文心兰",
	"https://baike.baidu.com/item/文殊兰",
	"https://baike.baidu.com/item/旱金莲",
	"https://baike.baidu.com/item/时钟花",
	"https://baike.baidu.com/item/曼陀罗",
	"https://baike.baidu.com/item/月光花",
	"https://baike.baidu.com/item/月见草",
	"https://baike.baidu.com/item/木兰花",
	"https://baike.baidu.com/item/木芙蓉",
	"https://baike.baidu.com/item/朱顶红",
	"https://baike.baidu.com/item/杜鹃花",
	"https://baike.baidu.com/item/松叶菊",
	"https://baike.baidu.com/item/松果菊",
	"https://baike.baidu.com/item/松红梅",
	"https://baike.baidu.com/item/栀子花",
	"https://baike.baidu.com/item/桃金娘",
	"https://baike.baidu.com/item/桉叶藤",
	"https://baike.baidu.com/item/梭鱼草",
	"https://baike.baidu.com/item/榆叶梅",
	"https://baike.baidu.com/item/毛地黄",
	"https://baike.baidu.com/item/水石榕",
	"https://baike.baidu.com/item/水鬼蕉",
	"https://baike.baidu.com/item/油菜花",
	"https://baike.baidu.com/item/洛神花",
	"https://baike.baidu.com/item/活血丹",
	"https://baike.baidu.com/item/海仙花",
	"https://baike.baidu.com/item/海杧果",
	"https://baike.baidu.com/item/海石竹",
	"https://baike.baidu.com/item/海芒果",
	"https://baike.baidu.com/item/滇山茶",
	"https://baike.baidu.com/item/火炬树",
	"https://baike.baidu.com/item/火烧花",
	"https://baike.baidu.com/item/火焰兰",
	"https://baike.baidu.com/item/火焰木",
	"https://baike.baidu.com/item/火绒草",
	"https://baike.baidu.com/item/炮仗花",
	"https://baike.baidu.com/item/点地梅",
	"https://baike.baidu.com/item/爆仗竹",
	"https://baike.baidu.com/item/狗娃花",
	"https://baike.baidu.com/item/狗牙花",
	"https://baike.baidu.com/item/狗舌草",
	"https://baike.baidu.com/item/独占春",
	"https://baike.baidu.com/item/猫尾草",
	"https://baike.baidu.com/item/玉簪花",
	"https://baike.baidu.com/item/珊瑚藤",
	"https://baike.baidu.com/item/珍珠梅",
	"https://baike.baidu.com/item/琉璃苣",
	"https://baike.baidu.com/item/瓜叶菊",
	"https://baike.baidu.com/item/番红花",
	"https://baike.baidu.com/item/白晶菊",
	"https://baike.baidu.com/item/白睡莲",
	"https://baike.baidu.com/item/百子莲",
	"https://baike.baidu.com/item/百日草",
	"https://baike.baidu.com/item/矢车菊",
	"https://baike.baidu.com/item/矮牵牛",
	"https://baike.baidu.com/item/矮雪轮",
	"https://baike.baidu.com/item/石仙桃",
	"https://baike.baidu.com/item/石楠花",
	"https://baike.baidu.com/item/石榴花",
	"https://baike.baidu.com/item/硫华菊",
	"https://baike.baidu.com/item/碧玉兰",
	"https://baike.baidu.com/item/福禄考",
	"https://baike.baidu.com/item/禾雀花",
	"https://baike.baidu.com/item/米兰花",
	"https://baike.baidu.com/item/紫娇花",
	"https://baike.baidu.com/item/紫玉兰",
	"https://baike.baidu.com/item/紫罗兰",
	"https://baike.baidu.com/item/紫薇花",
	"https://baike.baidu.com/item/繁星花",
	"https://baike.baidu.com/item/红丁香",
	"https://baike.baidu.com/item/红千层",
	"https://baike.baidu.com/item/红瑞木",
	"https://baike.baidu.com/item/红睡莲",
	"https://baike.baidu.com/item/绣球花",
	"https://baike.baidu.com/item/罂粟花",
	"https://baike.baidu.com/item/羊蹄甲",
	"https://baike.baidu.com/item/美人蕉",
	"https://baike.baidu.com/item/美女樱",
	"https://baike.baidu.com/item/羽扇豆",
	"https://baike.baidu.com/item/肥皂草",
	"https://baike.baidu.com/item/臭牡丹",
	"https://baike.baidu.com/item/芙蓉菊",
	"https://baike.baidu.com/item/芙蓉葵",
	"https://baike.baidu.com/item/花木蓝",
	"https://baike.baidu.com/item/花毛茛",
	"https://baike.baidu.com/item/花毛莨",
	"https://baike.baidu.com/item/花烟草",
	"https://baike.baidu.com/item/花菱草",
	"https://baike.baidu.com/item/茉莉花",
	"https://baike.baidu.com/item/荷兰花",
	"https://baike.baidu.com/item/荷兰菊",
	"https://baike.baidu.com/item/荷包花",
	"https://baike.baidu.com/item/萍蓬草",
	"https://baike.baidu.com/item/萼距花",
	"https://baike.baidu.com/item/蒜香藤",
	"https://baike.baidu.com/item/蓝目菊",
	"https://baike.baidu.com/item/蓝花楹",
	"https://baike.baidu.com/item/蓝雪花",
	"https://baike.baidu.com/item/蔓花生",
	"https://baike.baidu.com/item/蔷薇花",
	"https://baike.baidu.com/item/藏红花",
	"https://baike.baidu.com/item/藿香蓟",
	"https://baike.baidu.com/item/虎刺梅",
	"https://baike.baidu.com/item/虞美人",
	"https://baike.baidu.com/item/蝴蝶兰",
	"https://baike.baidu.com/item/蝴蝶花",
	"https://baike.baidu.com/item/蟹爪兰",
	"https://baike.baidu.com/item/西番莲",
	"https://baike.baidu.com/item/贝壳花",
	"https://baike.baidu.com/item/迎春花",
	"https://baike.baidu.com/item/还亮草",
	"https://baike.baidu.com/item/迷迭香",
	"https://baike.baidu.com/item/郁金香",
	"https://baike.baidu.com/item/醉鱼草",
	"https://baike.baidu.com/item/金丝桃",
	"https://baike.baidu.com/item/金丝梅",
	"https://baike.baidu.com/item/金光菊",
	"https://baike.baidu.com/item/金凤花",
	"https://baike.baidu.com/item/金樱子",
	"https://baike.baidu.com/item/金盏花",
	"https://baike.baidu.com/item/金盏菊",
	"https://baike.baidu.com/item/金缕梅",
	"https://baike.baidu.com/item/金花茶",
	"https://baike.baidu.com/item/金苞花",
	"https://baike.baidu.com/item/金钟花",
	"https://baike.baidu.com/item/金铃花",
	"https://baike.baidu.com/item/金银木",
	"https://baike.baidu.com/item/金银花",
	"https://baike.baidu.com/item/金露梅",
	"https://baike.baidu.com/item/金鱼草",
	"https://baike.baidu.com/item/金鸡菊",
	"https://baike.baidu.com/item/钓钟柳",
	"https://baike.baidu.com/item/铁线莲",
	"https://baike.baidu.com/item/银合欢",
	"https://baike.baidu.com/item/锦带花",
	"https://baike.baidu.com/item/锦鸡儿",
	"https://baike.baidu.com/item/长寿花",
	"https://baike.baidu.com/item/长春花",
	"https://baike.baidu.com/item/闭鞘姜",
	"https://baike.baidu.com/item/非洲菊",
	"https://baike.baidu.com/item/韩信草",
	"https://baike.baidu.com/item/风信子",
	"https://baike.baidu.com/item/风毛菊",
	"https://baike.baidu.com/item/风铃草",
	"https://baike.baidu.com/item/飘香藤",
	"https://baike.baidu.com/item/飞燕草",
	"https://baike.baidu.com/item/香雪球",
	"https://baike.baidu.com/item/马利筋",
	"https://baike.baidu.com/item/马蹄莲",
	"https://baike.baidu.com/item/鬼罂粟",
	"https://baike.baidu.com/item/鸡冠花",
	"https://baike.baidu.com/item/鸡矢藤",
	"https://baike.baidu.com/item/鸡蛋花",
	"https://baike.baidu.com/item/鹅掌草",
	"https://baike.baidu.com/item/鹤望兰",
	"https://baike.baidu.com/item/黄刺玫",
	"https://baike.baidu.com/item/黄水仙",
	"https://baike.baidu.com/item/黄钟木",
	"https://baike.baidu.com/item/黑心菊",
	"https://baike.baidu.com/item/龙吐珠",
	"https://baike.baidu.com/item/龙船花",
	"https://baike.baidu.com/item/东京樱花",
	"https://baike.baidu.com/item/东北百合",
	"https://baike.baidu.com/item/丽格海棠",
	"https://baike.baidu.com/item/二乔木兰",
	"https://baike.baidu.com/item/五爪金龙",
	"https://baike.baidu.com/item/令箭荷花",
	"https://baike.baidu.com/item/侧金盏花",
	"https://baike.baidu.com/item/倒挂金钟",
	"https://baike.baidu.com/item/假龙头花",
	"https://baike.baidu.com/item/光叶子花",
	"https://baike.baidu.com/item/兜唇石斛",
	"https://baike.baidu.com/item/北黄花菜",
	"https://baike.baidu.com/item/十大功劳",
	"https://baike.baidu.com/item/卷丹百合",
	"https://baike.baidu.com/item/厚萼凌霄",
	"https://baike.baidu.com/item/吊灯扶桑",
	"https://baike.baidu.com/item/地涌金莲",
	"https://baike.baidu.com/item/垂丝海棠",
	"https://baike.baidu.com/item/多花紫藤",
	"https://baike.baidu.com/item/大白杜鹃",
	"https://baike.baidu.com/item/大花紫薇",
	"https://baike.baidu.com/item/大花萱草",
	"https://baike.baidu.com/item/大花蕙兰",
	"https://baike.baidu.com/item/尖叶杜英",
	"https://baike.baidu.com/item/巴西鸢尾",
	"https://baike.baidu.com/item/带叶兜兰",
	"https://baike.baidu.com/item/德国鸢尾",
	"https://baike.baidu.com/item/斑叶堇菜",
	"https://baike.baidu.com/item/日本晚樱",
	"https://baike.baidu.com/item/橙红茑萝",
	"https://baike.baidu.com/item/沙漠玫瑰",
	"https://baike.baidu.com/item/海州常山",
	"https://baike.baidu.com/item/湖北海棠",
	"https://baike.baidu.com/item/球花石斛",
	"https://baike.baidu.com/item/琴叶珊瑚",
	"https://baike.baidu.com/item/白三叶草",
	"https://baike.baidu.com/item/白车轴草",
	"https://baike.baidu.com/item/白马蹄莲",
	"https://baike.baidu.com/item/短毛独活",
	"https://baike.baidu.com/item/碧冬茄属",
	"https://baike.baidu.com/item/紫花地丁",
	"https://baike.baidu.com/item/红花檵木",
	"https://baike.baidu.com/item/红花石斛",
	"https://baike.baidu.com/item/红花银桦",
	"https://baike.baidu.com/item/红花龙胆",
	"https://baike.baidu.com/item/红鸡蛋花",
	"https://baike.baidu.com/item/美国薄荷",
	"https://baike.baidu.com/item/翅荚决明",
	"https://baike.baidu.com/item/荷包牡丹",
	"https://baike.baidu.com/item/荷花玉兰",
	"https://baike.baidu.com/item/西府海棠",
	"https://baike.baidu.com/item/贴梗海棠",
	"https://baike.baidu.com/item/软枝黄蝉",
	"https://baike.baidu.com/item/金边瑞香",
	"https://baike.baidu.com/item/锦绣杜鹃",
	"https://baike.baidu.com/item/非洲凤仙",
	"https://baike.baidu.com/item/鸡冠刺桐",
	"https://baike.baidu.com/item/鸳鸯茉莉",
	"https://baike.baidu.com/item/鹿角海棠",
	"https://baike.baidu.com/item/麝香百合",
	"https://baike.baidu.com/item/黄槐决明",
	"https://baike.baidu.com/item/黄花鸢尾",
	"https://baike.baidu.com/item/串叶松香草",
	"https://baike.baidu.com/item/半钟铁线莲",
	"https://baike.baidu.com/item/华北珍珠梅",
	"https://baike.baidu.com/item/华北耧斗菜",
	"https://baike.baidu.com/item/单瓣黄刺玫",
	"https://baike.baidu.com/item/四季秋海棠",
	"https://baike.baidu.com/item/垂枝红千层",
	"https://baike.baidu.com/item/垂笑君子兰",
	"https://baike.baidu.com/item/多叶羽扇豆",
	"https://baike.baidu.com/item/多花指甲兰",
	"https://baike.baidu.com/item/多花野牡丹",
	"https://baike.baidu.com/item/多被银莲花",
	"https://baike.baidu.com/item/大花六道木",
	"https://baike.baidu.com/item/大花威灵仙",
	"https://baike.baidu.com/item/大花美人蕉",
	"https://baike.baidu.com/item/大花蓝盆花",
	"https://baike.baidu.com/item/大花金鸡菊",
	"https://baike.baidu.com/item/大花马齿苋",
	"https://baike.baidu.com/item/彩色马蹄莲",
	"https://baike.baidu.com/item/瓣蕊唐松草",
	"https://baike.baidu.com/item/白花夹竹桃",
	"https://baike.baidu.com/item/粉花月见草",
	"https://baike.baidu.com/item/粉花绣线菊",
	"https://baike.baidu.com/item/粉苞酸脚杆",
	"https://baike.baidu.com/item/红花文殊兰",
	"https://baike.baidu.com/item/红花羊蹄甲",
	"https://baike.baidu.com/item/红花醡浆草",
	"https://baike.baidu.com/item/红花锦鸡儿",
	"https://baike.baidu.com/item/美丽月见草",
	"https://baike.baidu.com/item/羽叶薰衣草",
	"https://baike.baidu.com/item/蓝花鼠尾草",
	"https://baike.baidu.com/item/达乌里秦艽",
	"https://baike.baidu.com/item/达乌里黄耆",
	"https://baike.baidu.com/item/金焰绣线菊",
	"https://baike.baidu.com/item/非洲凌霄属",
	"https://baike.baidu.com/item/非洲紫罗兰",
	"https://baike.baidu.com/item/麻叶绣线菊",
	"https://baike.baidu.com/item/黄绿贝母兰",
	"https://baike.baidu.com/item/黄花夹竹桃",
	"https://baike.baidu.com/item/黄花风铃木",
	"https://baike.baidu.com/item/黑心金光菊",
	"https://baike.baidu.com/item/齿缘吊钟花",
	"https://baike.baidu.com/item/垂枝大叶早樱",
	"https://baike.baidu.com/item/新几内亚凤仙",
	"https://baike.baidu.com/item/粉紫重瓣木槿",
	"https://baike.baidu.com/item/阿拉伯婆婆纳",
    ]
    default_domain = "https://baike.baidu.com"

    def append_file_data(self,filename,data):
	open(filename,"a").write(data+"\n")

    def parse(self, response):
        #print response.text
        data = response.xpath("//div[@class='album-list']/div/a/@href").extract()
	if (data[0]):
		album_list_url = self.default_domain + data[0]
		print album_list_url,"album_list_url"
	#        album_list_url = "http://127.0.0.1/s2.html"
		yield Request(url=album_list_url,callback=self.parse_album_list, dont_filter=True)
	else:
		append_file_data("error.log",response.url)

    def parse_album_list(self, response):

        album_num = response.xpath("//span[@class='album-num num']/text()").extract()
        pic_num = response.xpath("//span[@class='pic-num num']/text()").extract()
        albums_title = response.xpath("//div[@class='album-title yahei']").extract()
        album_list = response.xpath("//div[@class='pic-list']")
	for album_item in album_list:
		pic_arr = album_item.xpath("a/@href").extract()
	#	for pic_item in pic_list: #loop get more album
		first_pic_url = self.default_domain + pic_arr[0]
		matchs = re.findall("pic/([^/]+)/(\d+)/(\d+).*",first_pic_url)
		#print matchs,"matchs"
		#f_name_album_data = urllib.unquote(matchs[0][0])+","+matchs[0][1]+","+matchs[0][2]
		#self.append_file_data("all_name_album.log",f_name_album_data)
		data_name = urllib.unquote(matchs[0][0])
		flo_name = matchs[0][1]
	#	if not os.path.exists(data_name):
	#		os.makedirs(data_name)
	#	self.append_file_data(data_name+"/"+flo_name+".log",matchs[0][2])
		print first_pic_url,"first_pic_url"
	#        first_pic_url = "http://127.0.0.1/s3.html"
		yield Request(url=first_pic_url,callback=self.parse_pic_page, dont_filter=True)

    def parse_pic_page(self, response):
#	print "response.url", response.url # get the pic (sort,album,pic)
	matchs = re.findall("pic/([^/]+)/(\d+)/(\d+).*",response.url)
	data_name = urllib.unquote(matchs[0][0])
	flo_name = matchs[0][1]
	album_name = matchs[0][2]
        pic_data = response.text
        match = re.findall("PictureDialog\.getInstance\(\)\.show\(\{[\s\S]* albums: (\{\".+\}\}),",pic_data)
        pic_url_list = []
	pic_url_data = ""
        pic_list = json.loads(match[0])
        for pic_item in pic_list[album_name]['pictures']:
                pic_size = str(pic_item['type']['oriWithWater'])
	#	print pic_item,"------\n pic_size:",pic_size
                pic_url = pic_item['sizes'][pic_size]['url']
                pic_url_list.append(pic_url)
		pic_url_data = pic_url_data + "\n" + pic_url
        print pic_url_list,"pic_url_list"
	if not os.path.exists(data_name):
		os.makedirs(data_name)
	self.append_file_data("download/"+data_name+"/data.log",pic_url_data)
	relation_data = {album_name:pic_url_list}
	self.append_file_data("download/"+data_name+"/"+flo_name+".log",json.dumps(relation_data))
        #return pic_url_list
